### ISSUE TITLE
Falta de requisito envolvendo pagamento do Ticket Machine

### ISSUE THREAD

**Issue by Rabuiat** [Rabuiat/Source-Code-Inspection#1]
Tipo de defeito: Omissão

Gravidade do defeito: Crítico

Local do defeito: 1

Descrição do defeito: Falta detalhes de requisitos do produto: existirão no sistema outras formas de pagamento possíveis além de dinheiro vivo? Quando o cliente insere a quantia errada de dinheiro (a mais ou a menos), como o sistema se comportará?
Não fica claro por quanto tempo a máquina manterá a soma total da quantidade de dinheiro.

**Comment by Rabuiat** [comment]
Tipo de defeito: Inconsistência 

Gravidade do defeito: Médio

Descrição do defeito: Diagrama de casos de uso não está de acordo com a descrição de requisitos (não foi mencionado troco no texto)

**Comment by Rabuiat** [comment]
Tipo de defeito: Fato incorreto

Gravidade do defeito: Baixo

Descrição do defeito: Um cliente não deve solicitar troco, a máquina/vendedor sempre devolve sem necessidade de botão (de acordo com a quantidade de bilhetes solicitados)

**Comment by Rabuiat** [comment]
Tipo de defeito: Ambiguidade

Gravidade do defeito: Médio

Local do defeito no documento: 1.3.1

Descrição do defeito: Não é possível saber se o valor de saldo total disponível citado é referente ao saldo de compra ou da máquina.

**Comment by Rabuiat** [comment]
Tipo de defeito: Erro de fluxo

Gravidade do defeito: Baixo

Local do defeito no documento: 1.3.1

Descrição do defeito: Se o sistema não aceita a nota, volta para o passo 6, que exibe saldo atual.

**Comment by Rabuiat** [comment]
Tipo de defeito: Ambiguidade

Gravidade de defeito: Baixo 

Local do defeito no documento: 1.3.3

Descrição do defeito: Ao solicitar troco, o sistema devolve o troco, zera o saldo e exibe o mesmo na tela, o que é desnecessário.

**Comment by Rabuiat** [comment]
Tipo de defeito: Inconsistência

Gravidade de defeito: Alta

Local do defeito: 1.4.1

Descrição do defeito: No protótipo, é apresentado um campo de texto para inserção de valor, mas na especificação de requisitos a máquina deve receber o valor em dinheiro através de um dispositivo.

**Comment by freddysaar** [comment]
Resolvido.
