### ISSUE TITLE
Diagramas de sequência fora das especificações

### ISSUE THREAD

**Issue by Rabuiat** [Rabuiat/Source-Code-Inspection#10]
Tipo do defeito: Inconsistência 

Gravidade do defeito: Baixo

Locais do defeito: 2.3, 2.4, 2.5

Descrição do defeito:  Diagramas de sequência não correspondem aos seus fluxos principais. Exemplo: <<create>> é utilizado demasiadamente no Solicitar Troco.

**Comment by freddysaar** [comment]
Diagramas de Sequência corrigidos.
