### ISSUE TITLE
Diagrama de casos não corresponde aos requisitos

### ISSUE THREAD

**Issue by Rabuiat** [Rabuiat/Source-Code-Inspection#2]
Tipo de defeito: Inconsistência 

Gravidade do defeito: Médio

Local do defeito no documento:  1.2

Descrição do defeito: Diagrama de casos de uso não está de acordo com a descrição de requisitos (não foi mencionado troco no texto).

**Comment by freddysaar** [comment]
Requisito adicionado: A máquina precisa devolver o dinheiro (troco) caso o cliente solicite.
