### ISSUE TITLE
Requisito botão para solicitação de troco

### ISSUE THREAD

**Issue by Rabuiat** [Rabuiat/Source-Code-Inspection#3]
Tipo de defeito: Fato incorreto

Gravidade do defeito: Baixa

Local do defeito: 1.2

Descrição do defeito: Um cliente não deve solicitar troco, a máquina/vendedor sempre devolve sem necessidade de botão (de acordo com a quantidade de bilhetes solicitados).

**Comment by freddysaar** [comment]
O cliente pode, sim, solicitar troco por um botão. Depois de análise da equipe, a funcionalidade foi mantida. O botão foi modificado para "Retirar Troco".
