### ISSUE TITLE
Ação de exibição desnecessária

### ISSUE THREAD

**Issue by Rabuiat** [Rabuiat/Source-Code-Inspection#6]
Tipo de defeito: Ambiguidade

Gravidade do defeito: Baixo

Local do defeito: 1.3.3

Descrição do defeito: Ao solicitar troco, o sistema devolve o troco, zera o saldo e exibe o mesmo na tela, o que é desnecessário.

**Comment by freddysaar** [comment]
Removido o último passo do Fluxo Principal do Caso de Uso 1.3.3 (Solicitar Troco)
