### ISSUE TITLE
Campo de texto fora da especificação

### ISSUE THREAD

**Issue by Rabuiat** [Rabuiat/Source-Code-Inspection#7]
Tipo de defeito: Inconsistência de dados

Gravidade do defeito: Alto

Local do defeito: 1.4.1

Descrição do defeito: No protótipo, é apresentado um campo de texto para inserção de valor, mas na especificação de requisitos a máquina deve receber o valor em dinheiro através de um dispositivo.

**Comment by freddysaar** [comment]
Protótipo modificado: campo de texto removido, 2 botões e visor de saldo mantidos.
