### ISSUE TITLE
Atributo desnecessário

### ISSUE THREAD

**Issue by Rabuiat** [Rabuiat/Source-Code-Inspection#9]
Tipo de defeito: Informação estranha

Gravidade do defeito: Baixo

Local do defeito: 2.1

Descrição do defeito: Na classe “PapelMoeda” o atributo quantidade não tem sentido, pois o atributo valor já caracteriza a quantia de dinheiro que será adicionada ao saldo. Logo, “getQuantidade()” também é irrelevante.

**Comment by freddysaar** [comment]
Atributo removido.
